### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by jaideraf** [vitorsilverio/libraryapi#46]
Antes das mudanças submetidas a pouco, fui tentar diagnosticar onde estava o problema nesta requisição: https://libraryapi-demo.herokuapp.com/pergamum/xml?url=https://pergamum.ufc.br/pergamum&id=2 . No terminal, dá a seguinte mensagem: 

```Shell
INFO:     127.0.0.1:42722 - "GET /pergamum/xml?url=https://pergamum.ufc.br/pergamum&id=2 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File ".local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File ".local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File ".local/lib/python3.10/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File ".local/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File ".local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File ".local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File ".local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File ".local/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File ".local/lib/python3.10/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File ".local/lib/python3.10/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File ".local/lib/python3.10/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File ".local/lib/python3.10/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File ".local/lib/python3.10/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "libraryapi/./app/main.py", line 27, in get_marc_xml
    pergamumDownloader.get_marc_xml(url, id),
  File "libraryapi/./libraryapi/pergamum.py", line 188, in get_marc_xml
    self.build_record(url, id), namespace=True
  File "libraryapi/./libraryapi/pergamum.py", line 179, in build_record
    return Conversor.convert_dados_marc_to_record(dados_marc, id)
  File "libraryapi/./libraryapi/pergamum.py", line 134, in convert_dados_marc_to_record
    Conversor.build_field(paragrafo, indicador, descricao)
  File "libraryapi/./libraryapi/pergamum.py", line 94, in build_field
    [[subfield[0], subfield[2:]] for subfield in descricao[1:].split("$")]
  File "libraryapi/./libraryapi/pergamum.py", line 94, in <listcomp>
    [[subfield[0], subfield[2:]] for subfield in descricao[1:].split("$")]
IndexError: string index out of range
```
Fazendo uma consulta com o wget: 
```Shell
wget -O- --quiet --waitretry=3600 \
  --header='Content-Type: text/xml; charset=utf-8' \
  --post-data="<soapenv:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:urn=\"urn:busca_marcwsdl\">
     <soapenv:Header/>
     <soapenv:Body>
        <urn:busca_marc soapenv:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">
           <codigo_acervo_temp xsi:type=\"xsd:int\">2</codigo_acervo_temp>
        </urn:busca_marc>
     </soapenv:Body>
  </soapenv:Envelope>" "https://pergamum.ufc.br/pergamum/web_service/servidor_ws.php?wsdl" | sed -E 's/.*<return.*?>//g
              s/<\/return>.*//g
              s/&lt;br\s?\/?\s?&gt;//g
              s/&lt;(\/?Dados_marc|\/?paragrafo|\/?indicador|\/?descricao)&gt;/<\1>/g
              s/&lt;\?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;\?&gt;/<?xml version="1.0" encoding="UTF-8"?>/g
              s/[\d1-\d31]|/ /g' | iconv -f ISO-8859-1 -t UTF-8
```
Retorna o seguinte: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
      <Dados_marc>
                  <paragrafo>001</paragrafo>
                  <indicador>   </indicador>
                  <descricao>2</descricao>
                  <paragrafo>003</paragrafo>
                  <indicador>   </indicador>
                  <descricao>BR-FoUFC </descricao>
                  <paragrafo>005</paragrafo>
                  <indicador>   </indicador>
                  <descricao>20191202212947.0 </descricao>
                  <paragrafo>008</paragrafo>
                  <indicador>   </indicador>
                  <descricao>041209s1990    mgb#   ###   #000 0#por#d </descricao>
                  <paragrafo>020</paragrafo>
                  <indicador>   </indicador>
                  <descricao>$c (Broch.) </descricao>
                  <paragrafo>040</paragrafo>
                  <indicador>   </indicador>
                  <descricao>$a BR-FoUFC $c BR-FoUFC </descricao>
                  <paragrafo>082</paragrafo>
                  <indicador>0 4</indicador>
                  <descricao>$a 330.122    $2 20 </descricao>
                  <paragrafo>090</paragrafo>
                  <indicador>   </indicador>
                  <descricao>$a 330.122    $b S663c    $8 1 </descricao>
                  <paragrafo>100</paragrafo>
                  <indicador>1  </indicador>
                  <descricao>$a Sodré, Nelson Werneck,   $d 1911-1999 </descricao>
                  <paragrafo>245</paragrafo>
                  <indicador>1 0</indicador>
                  <descricao>$a Capitalismo e revolucao burguesa no Brasil /  $c Nelson Werneck Sodre. </descricao>
                  <paragrafo>260</paragrafo>
                  <indicador>   </indicador>
                  <descricao>$a Belo Horizonte:   $b Oficina de Livros,   $c 1990.   </descricao>
                  <paragrafo>300</paragrafo>
                  <indicador>   </indicador>
                  <descricao>$a 203 p.   </descricao>
      <paragrafo>650</paragrafo>
      <indicador>0 4</indicador>
      <descricao>$a Capitalismo </descricao>
      </Dados_marc>
```
Tem alguma ideia de onde está o problema?

**Comment by vitorsilverio** [comment]
@jaideraf eu me lembro que você mudou como pegava os valores de um split, eu lembro que fiz de um jeito para não cair em condições que o indice não existisse. Preciso ver o antes e depois da parte que foi alterada para ver onde quebrou a lógica

**Comment by jaideraf** [comment]
Nunca alterei essa parte do código, minhas alterações foram em outras partes: https://github.com/vitorsilverio/libraryapi/commit/cb41fca2d029a7866299de5de77da9986872358e, https://github.com/vitorsilverio/libraryapi/commit/2cc157768baa951d7999d0941d18f1c107082ef8, https://github.com/vitorsilverio/libraryapi/commit/00932895abbf38271eb77a876de8871555e2e27b, 
https://github.com/vitorsilverio/libraryapi/commit/3c6a081a082fffb7c122bd338c16159e2ba6c5bb.

Só mudei agora nessa última submissão o nome da variável, ou seja, nem foi merged ainda. Comecei a alterar o código justamente para tentar resolver este problema. Se quiser testar, clone uma versão antiga.

**Comment by jaideraf** [comment]
Essa linha é a original tua (que ainda está intocada no momento que estou escrevendo é a que está em "produção" no heroku):

`[[s[0], s[2:].strip()] for s in descricao[1:].split("$")]`
